version: '3.1'
services:
    # We can add more services if we need them, such as DB, cache, etc for ease of development
    api:
        build:
            context: .
        restart: always
        ports:
            - 3000:3000
            - 5858:5858
        working_dir: /var/www
        volumes:
            - ./:/var/www:cached
        logging:
            options:
                max-size: '10m'
                max-file: '10'
        command: yarn run dev
